config/routes.rb
Rails.application.routes.draw do
  root 'mainpage#index'   

  get "/mainpage/index", to: 'mainpage#index'  
  get "/mainpage/bio", to: 'mainpage#bio'


  resources :tasks do
    resources :points
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/point.rb
class Point < ApplicationRecord
	belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :points, dependent: :destroy


    validates :title, length: { minimum: 3 }, presence: true, uniqueness: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mainpage_controller.rb
class MainpageController < ApplicationController
	def index
		
	end
	def bio

	end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def create
    @task = Task.find(params[:task_id])
    @point = @task.points.create(point_params)
    redirect_to task_path(@task)
  end
  def destroy
    @task = Task.find(params[:task_id])
    @point = Point.find(params[:id])
    @point.destroy

    redirect_to task_points_path(@task)
  end
  def index
    @task = Task.find(params[:task_id])
    @points_finished = @task.points.where(finished: true)
    @points_no_finished = @task.points.where(finished: false)  
  end
  
  def edit
    @task = Task.find(params[:task_id])
    @point = Point.find(params[:id]) 

  end

  def update
    @task = Task.find(params[:task_id])
    @point = Point.find(params[:id]) 

    if @point.update(point_params)
      redirect_to task_path(@task)
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def point_params
      params.require(:point).permit(:title, :finished)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @thems = 0
    @tasks = Task.all
    @task = Task.new

  end

  def show
    @task = Task.find(params[:id])
    @points_finished = @task.points.where(finished: true)
    @points_no_finished = @task.points.where(finished: false)
  end

  def new
      @task = Task.new
      @new = 1


  end

  def create
    @task = Task.new(article_params)
    if @task.save
        redirect_to tasks_path
    else 
      render :new , status: :unprocessable_entity
    end

  end

  def edit
    @task = Task.find(params[:id])   

  end

  def update
    @task = Task.find(params[:id])

    if @task.update(article_params)
      redirect_to tasks_path
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path, status: :see_other

  end

  private
    def article_params
      params.require(:task).permit(:title, :body, :complit_procent)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_of_tasks_helper.rb
module ListOfTasksHelper
end

app/helpers/mainpage_helper.rb
module MainpageHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpisokBl9dskihProgektov</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main >
      <%= render 'layouts/shared/menu' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/shared/_menu.html.erb
<nav class="bg-sky-100 border-gray-200 dark:bg-gray-900">
    <div class="flex flex-wrap items-center justify-between max-w-screen-xl mx-auto p-4">
        <a href="https://github.com/Vasi1ek745" target="_blank" class="flex items-center">
            <img src="assets/logo-github.1024x1024.png" class="h-8 mr-3" alt="Github logo" />
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">My github</span>
        </a>
        <div class="flex items-center md:order-2">
            <a href="#" class="text-gray-800 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2 md:px-5 md:py-2.5 mr-1 md:mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800">Login</a>
            <a href="#" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 md:px-5 md:py-2.5 mr-1 md:mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Sign up</a>
            <button data-collapse-toggle="mega-menu" type="button" class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mega-menu" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg aria-hidden="true" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
            </button>
        </div>
        <div id="mega-menu" class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1">
            <ul class="flex flex-col mt-4 font-medium md:flex-row md:space-x-8 md:mt-0">
                <li>
                    <a href="<%= root_path %>" class="block py-2 pl-3 pr-4 text-blue-600 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-blue-500 md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700" aria-current="page">Главная страница</a>
                </li>
                <li>
                    <button id="mega-menu-dropdown-button" data-dropdown-toggle="mega-menu-dropdown" class="flex items-center justify-between w-full py-2 pl-3 pr-4 font-medium text-gray-900 border-b border-gray-100 md:w-auto hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700">
                        Проекты <svg aria-hidden="true" class="w-5 h-5 ml-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                    </button>
                    <div id="mega-menu-dropdown" class="absolute z-10 grid hidden w-auto grid-cols-2 text-sm bg-white border border-gray-100 rounded-lg shadow-md dark:border-gray-700 md:grid-cols-3 dark:bg-gray-700">
                        <div class="p-4 pb-0 text-gray-900 md:pb-4 dark:text-white">
                            <ul class="space-y-4" aria-labelledby="mega-menu-dropdown-button">
                                <li>
                                    <a href="<%= tasks_path %>" class="text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-500">
                                        Список проектов
                                    </a>
                                </li>
                                <li>
                                    <a href="<%= new_task_path %>" class="text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-500">
                                        Добавить новый проект
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-500">
                                        Resources
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-500">
                                        Pro Version
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </li>
                <li>
                    <a href="<%= new_task_path %>" class="block py-2 pl-3 pr-4 text-gray-900 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700">Добавить проект</a>
                </li>
                <li>
                    <a href="<%= mainpage_bio_path %>" class="block py-2 pl-3 pr-4 text-gray-900 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-600 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-blue-500 md:dark:hover:bg-transparent dark:border-gray-700">Контакты</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/list_of_tasks/example.html.erb
<nav class="flex  bg-gray-800">
  <div class="max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class=" relative flex h-16 items-center ">
      <div class="flex ">
        <div class="flex flex-shrink-0 ">
          <img class="block h-8 w-auto lg:hidden" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
          <img class="hidden h-8 w-auto lg:block" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="#" class="bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium" aria-current="page">Светлая тема</a>
    
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</nav>

<div class="flex flex-col"> 

	<div class="flex items-center justify-center w-screen h-screen font-medium">
		<% if @thems == 0 %>
		  	<div class="flex flex-grow items-center justify-center h-full text-gray-600 bg-gray-100">
				<!-- Component Start -->
				<div class="max-w-full p-8 bg-white rounded-lg shadow-lg w-96">
				<div class="flex items-center mb-6">
					<svg class="h-8 w-8 text-indigo-500 stroke-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
					</svg>
					<h4 class="font-semibold ml-3 text-lg">Список блядских проектов</h4>
			</div>
			

			<% @tasks.each do |tasks| %>
			<div>
				<input class="hidden" type="checkbox" id= <%= tasks.id %> >
				<label class="flex items-center h-10 px-2 rounded cursor-pointer hover:bg-gray-100" for=<%= tasks.id %>>
					<span class="flex items-center justify-center w-5 h-5 text-transparent border-2 border-gray-300 rounded-full">
						<svg class="w-4 h-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
							<path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
						</svg>
					</span>
					<span class="ml-4 text-sm"> <%= tasks.body %> </span>
				</label>	
			</div>
			  <% end %>

			<button class="flex items-center w-full h-8 px-2 mt-2 text-sm font-medium rounded">
				<svg class="w-5 h-5 text-gray-400 fill-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
				</svg>
				<input class="flex-grow h-8 ml-4 bg-transparent focus:outline-none font-medium" type="text" placeholder="add a new task">
			</button>
			</div>
			<!-- Component End  -->
			</div>

		<% else %> 
			<div class="flex flex-grow items-center justify-center bg-gray-900 h-full">
			<!-- Component Start -->
			<div class="max-w-full p-8 bg-gray-800 rounded-lg shadow-lg w-96 text-gray-200">
			<div class="flex items-center mb-6">
				<svg class="h-8 w-8 text-indigo-500 stroke-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
				</svg>
				<h4 class="font-semibold ml-3 text-lg">Sam's Jobs</h4>
			</div>
			<div>
				<input class="hidden" type="checkbox" id="task_6" checked>
				<label class="flex items-center h-10 px-2 rounded cursor-pointer hover:bg-gray-900" for="task_6">
					<span class="flex items-center justify-center w-5 h-5 text-transparent border-2 border-gray-500 rounded-full">
						<svg class="w-4 h-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
							<path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
						</svg>
					</span>
					<span class="ml-4 text-sm">Trim the verge.</span>
				</label>	
			</div>
			<div>
				<input class="hidden" type="checkbox" id="task_7" checked>
				<label class="flex items-center h-10 px-2 rounded cursor-pointer hover:bg-gray-900" for="task_7">
					<span class="flex items-center justify-center w-5 h-5 text-transparent border-2 border-gray-500 rounded-full">
						<svg class="w-4 h-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
							<path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
						</svg>
					</span>
					<span class="ml-4 text-sm">Eavesdrop on Master Frodo & Gandalf.</span>
				</label>	
			</div>
			<div>
				<input class="hidden" type="checkbox" id="task_8">
				<label class="flex items-center h-10 px-2 rounded cursor-pointer hover:bg-gray-900" for="task_8">
					<span class="flex items-center justify-center w-5 h-5 text-transparent border-2 border-gray-500 rounded-full">
						<svg class="w-4 h-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
							<path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
						</svg>
					</span>
					<span class="ml-4 text-sm">Boil, mash, and stick potatoes in stew.</span>
				</label>	
			</div>
			<div>
				<input class="hidden" type="checkbox" id="task_9">
				<label class="flex items-center h-10 px-2 rounded cursor-pointer hover:bg-gray-900" for="task_9">
					<span class="flex items-center justify-center w-5 h-5 text-transparent border-2 border-gray-500 rounded-full">
						<svg class="w-4 h-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
							<path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
						</svg>
					</span>
					<span class="ml-4 text-sm">Carry Frodo.</span>
				</label>	
			</div>
			<div>
				<input class="hidden" type="checkbox" id="task_10">
				<label class="flex items-center h-10 px-2 rounded cursor-pointer hover:bg-gray-900" for="task_10">
					<span class="flex items-center justify-center w-5 h-5 text-transparent border-2 border-gray-500 rounded-full">
						<svg class="w-4 h-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
							<path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
						</svg>
					</span>
					<span class="ml-4 text-sm">Be all round legend.</span>
				</label>	
			</div>
			<button class="flex items-center w-full h-8 px-2 mt-2 text-sm font-medium rounded">
				<svg class="w-5 h-5 text-gray-400 fill-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
				</svg>
				<input class="flex-grow h-8 ml-4 bg-transparent focus:outline-none font-medium" type="text" placeholder="add a new task">
			</button>
			</div>
			<!-- Component End  -->

			</div> 
		<% end %>
	</div>	

</div>

app/views/mainpage/bio.html.erb
<div class="m-7"> 
    <h1 class="text-3xl">Контакты:</h1>

    <ul class="m-3 space-y-4 text-left text-gray-500 dark:text-gray-400">
        <li class="flex items-center space-x-3">
            <img class="h-9" src="/assets/telegram_icon.png">
            <a type="button" class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-full text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" href="https://t.me/vasiliy745" target="_blank">https://t.me/vasiliy745 </a>

        </li>
        <li class="flex items-center space-x-3">
            <img class="h-9" src="/assets/WhatsApp.png">
            <a type="button" class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-full text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"  > +79193623913 </a>
        </li>
        <li class="flex items-center space-x-3">
            <img class="h-9" src="/assets/cell-phone.svg">
            <a type="button" class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-full text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"  > +79193623913 </a>
        </li>
        <li class="flex items-center space-x-3">
            <img class="h-9" src="/assets/email.png">
            <a type="button" class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-full text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" href="mailto:LazukinVas@gmail.com" target="_blank">LazukinVas@gmail.com </a>
        </li>

    </ul>

</div>

app/views/points/index.html.erb
<div class="flex flex-col m-2">
    <div class="flex flex-col border border-gray-200 shadow-xl rounded max-w-lg my-2">
        <div class="flex m-2">
            <h1 class=" text-xl font-semibold text-gray-900 dark:text-white"> Планы:  </h1>
        </div>
         <% @points_no_finished.each do |point|%>
        <div class="flex flex-row justify-between">
            <div class="flex">
                <ul class="max-w-md space-y-1 m-2 text-lg text-gray-700 list-disc list-inside dark:text-gray-400">
                    <li> <%= point.title %> </li>
                </ul>
            </div>
            <div class="flex m-2">
                <div class="inline-flex rounded-md shadow-sm">
                    <div>
                        <%= link_to "Редактировать", edit_task_point_path(@task, point), class:"px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-l-lg hover:bg-gray-100 hover:text-blue-700  focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white" %>
                    </div>
                    <div>
                        <%= link_to "Удалить", task_point_path(@task, point)  , data: {turbo_method: :delete,turbo_confirm: "Are you sure?"}, 
                        class:"px-4 py-2 text-sm font-medium text-gray-900 bg-white border-t rounded-r-lg border-b border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 
                            dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white" %>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
    </div>
    <div class="flex flex-col border border-gray-200 shadow-xl rounded max-w-lg my-2">
        <div class="flex m-2">
            <h1 class=" text-xl font-semibold text-gray-900 dark:text-white"> Уже сделано:  </h1>
        </div>
         <% @points_finished.each do |point|%>
        <div class="flex flex-row justify-between">
            <div class="flex">
                <ul class="max-w-md space-y-1 m-2 text-lg text-gray-700 list-disc list-inside dark:text-gray-400">
                    <li> <%= point.title %> </li>
                </ul>
            </div>
            <div class="flex m-2">
                <div class="inline-flex rounded-md shadow-sm">
                    <div>
                        <%= link_to "Редактировать", edit_task_point_path(@task, point), class:"px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-l-lg hover:bg-gray-100 hover:text-blue-700  focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white" %>
                    </div>
                    <div>
                        <%= link_to "Удалить", task_point_path(@task, point)  , data: {turbo_method: :delete,turbo_confirm: "Are you sure?"}, 
                        class:"px-4 py-2 text-sm font-medium text-gray-900 bg-white border-t rounded-r-lg border-b border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 
                            dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white" %>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
    </div>

               
</div>
<div class="border border-gray-200 rounded-lg shadow-xl m-3 p-3 max-w-lg">
  <!-- начало формы для point -->

  <div class="m-2 flex flex-col">
    <h1 class="text-xl m-2 mb-5"> 
      Добавить
    </h1>

    <%= form_with model: [@task, @task.points.build] do |form| %>
   
    <div class="flex-col">
      <%= form.text_field :title , class:"m-2 rounded-lg shadow-xl", minlength: "3", required: true %>
    </div>
    <div class=" m-2 flex items-center ">
      <input id="point[finished]" type="checkbox" value="true" name="point[finished]" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
      <label for="point[finished]" class="ml-2 text-sm font-medium text-gray-900 dark:text-gray-300"> Выполнено </label>
    </div>
    <div class="m-2">
      <input type="submit" name="commit" value="ок" class="bg-indigo-400 hover:bg-slate-500 text-white font-bold py-2 px-4 rounded-full" data-disable-with="создать">
    </div>
    <% end %>
  </div>
</div>
    <!-- конец формы для point -->
</div>

app/views/points/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Points#new</h1>
  <p>Find me in app/views/points/new.html.erb</p>
</div>

app/views/tasks/edit.html.erb
<%= render 'tasks/shared/new_edit_form' %>

app/views/tasks/new.html.erb
<%= render 'tasks/shared/new_edit_form' %>